name: Dependabot auto-merge
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3' # 00:00 AM UTC
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependabot Auto Merge action
        uses: Automattic/vip-actions/dependabot-auto-merge@a56c9af7982ab638ed20b59b0b3a909f247d5f50
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
