name: Dependabot auto-merge
on:
  schedule:
    - cron: '0 0 * * 3' # 00:00 AM UTC
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependabot Auto Merge action
        uses: Automattic/vip-actions/dependabot-auto-merge@5580f2e382d9481640a46d48181618416ed2c96c
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
