name: Dependabot auto-merge
on: pull_request

# depend on ci.yaml workflow


permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    name: Automerge!
    # wait for ci to pass
    # https://github.community/t/how-to-get-the-status-of-a-specific-check/16241/2
    runs-on: ubuntu-latest
    # if the PR is created by dependabot
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
