name: Dependabot auto-merge
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3' # 00:00 AM UTC
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependabot Auto Merge action
        uses: Automattic/vip-actions/dependabot-auto-merge@803e5e3cc8173266cdb03931d1db82a35731f77f
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
