name: Dependabot auto-merge
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3' # 00:00 AM UTC
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependabot Auto Merge action
        uses: Automattic/vip-actions/dependabot-auto-merge@49879329d839f8bd6ad4a44c5d7e6f879a26f551
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
