name: Dependabot auto-merge
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3' # 00:00 AM UTC
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependabot Auto Merge action
        uses: Automattic/vip-actions/dependabot-auto-merge@e3b1c52f5a2de6950c56076e1a79ed863257f4e5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
